/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/main/resources/templates/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          dark: '#1B331C',
          accent: '#C79E5C',
          light: '#F8F7F0',
          success: '#407B4A',
          button: '#3a724b',
          active: '#e0b571',
        },
        'charbon-dark': '#1B3022',
        'charbon-green': '#3E7B4F',
        'charbon-light-green': '#4A8B5D',
        'charbon-beige': '#F8F7F0',
        'charbon-gold': '#D4A373',
        'charbon-accent': '#E2C28E',
        'charbon-light': '#4A8B5D',
        'on-surface': '#1a1c1c',
        'surface-container-lowest': '#ffffff',
        'secondary': '#5e5e5e',
        'background': '#faf9f9',
        'secondary-container': '#e2e2e2',
        'outline': '#747878',
        'surface-container': '#eeeeee',
        'swiss-red': '#E73C02',
        'success-green': '#00AA44',
        'border-gray': '#CCCCCC',
        'surface-container-high': '#e8e8e8',
        'surface-container-low': '#f4f3f3',
        'cv-dark-green': '#1a2e1a',
        'cv-cream': '#f9f8f3',
        'cv-gold': '#c5a059',
        'cv-accent': '#2d5a27',
        'cv-sidebar-green': '#1e3a2c',
        'cv-accent-green': '#3d633d',
        'cv-button-green': '#2d5a3c',
        'cv-bg-light': '#fdfcf7',
        'cv-gold-light': '#d4b483',
        'cv-text-muted': '#6b7280',
        'cv-sidebar-hover': '#2a4a37',
        'cv-primary-green': '#2d5a3f',
        'cv-accent-orange': '#d99a4e',
        'cv-border-cream': '#e5e3d8',
        'cv-status-green-bg': '#e6f4ea',
        'cv-status-green-text': '#1e7e34',
        'cv-status-yellow-bg': '#fef3c7',
        'cv-status-yellow-text': '#92400e',
        'cv-status-blue-bg': '#e0f2fe',
        'cv-status-blue-text': '#0369a1',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
