/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/main/resources/templates/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          dark: '#432818',
          accent: '#bb9457',
          light: '#FFF8F0',
          success: '#6f1d1b',
          button: '#99582a',
          active: '#ffe6a7',
        },
        'charbon-dark': '#432818',
        'charbon-green': '#6f1d1b',
        'charbon-light-green': '#99582a',
        'charbon-beige': '#FFF8F0',
        'charbon-gold': '#bb9457',
        'charbon-accent': '#ffe6a7',
        'charbon-light': '#99582a',
        'on-surface': '#1a1c1c',
        'surface-container-lowest': '#ffffff',
        'secondary': '#5e5e5e',
        'background': '#faf9f9',
        'secondary-container': '#e2e2e2',
        'outline': '#747878',
        'surface-container': '#eeeeee',
        'swiss-red': '#E73C02',
        'success-green': '#6f1d1b',
        'border-gray': '#CCCCCC',
        'surface-container-high': '#e8e8e8',
        'surface-container-low': '#f4f3f3',
        'cv-dark-green': '#432818',
        'cv-cream': '#FFF8F0',
        'cv-gold': '#bb9457',
        'cv-accent': '#6f1d1b',
        'cv-sidebar-green': '#432818',
        'cv-accent-green': '#6f1d1b',
        'cv-button-green': '#99582a',
        'cv-bg-light': '#FFF8F0',
        'cv-gold-light': '#ffe6a7',
        'cv-text-muted': '#6b7280',
        'cv-sidebar-hover': '#553a2a',
        'cv-primary-green': '#6f1d1b',
        'cv-accent-orange': '#bb9457',
        'cv-border-cream': '#e5e3d8',
        'cv-status-green-bg': '#fef3c7',
        'cv-status-green-text': '#92400e',
        'cv-status-yellow-bg': '#fef3c7',
        'cv-status-yellow-text': '#92400e',
        'cv-status-blue-bg': '#e0f2fe',
        'cv-status-blue-text': '#0369a1',
        sidebar: '#432818',
        sidebarHover: '#553a2a',
        accent: '#bb9457',
        pageBg: '#FFF8F0',
        inputBg: '#ffffff',
        primaryGreen: '#6f1d1b',
        bannerBg: '#fef3c7',
        'forest-green': '#432818',
        'leaf-green': '#6f1d1b',
        'action-green': '#99582a',
        'gold-light': '#ffe6a7',
        'amber-soft': '#bb9457',
        'forestry-dark': '#432818',
        'forestry-accent': '#bb9457',
        'forestry-bg': '#FFF8F0',
        'forestry-text': '#432818',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
